### ISSUE TITLE
Question regarding the WMO 4680 WaWa table icon 70

### ISSUE THREAD

**Issue by sirviot** [roe-dl/weathericons#1]
Is the symbol for WaWa code 70 pictured as three triangles in purpose, or should there be a single asterisk to represent snow instead?

**Comment by roe-dl** [comment]
The symbol of w<sub>a</sub>w<sub>a</sub> 70 has another meaning than ww 70. So the symbols are different:

WMO code | symbol | description
------------|--------|-------------
ww 70 | <img src="https://raw.githubusercontent.com/roe-dl/weathericons/master/ww-colored/wmo4677_ww70.svg" width="32px" /> | means intermittent light snow
w<sub>a</sub>w<sub>a</sub> 70 | <img src="https://raw.githubusercontent.com/roe-dl/weathericons/master/wawa-colored/wmo4680_wawa70.svg" width="32px" /> | means snow of unknown intensity.

See [WMO Manual on Codes. International Codes. Volume I.1](https://library.wmo.int/doc_num.php?explnum_id=10235) for more details, and there especially page A-444 for the w<sub>a</sub>w<sub>a</sub> symbols.

**Comment by sirviot** [comment]
So it is. Thank you very much for your help, and for pointing me to the correct page of the WMO:s publication. I will happily close this issue.
